# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "test the app and generate a code_coverage report"
  lane :test do
    scan(scheme: "GithubRepoList", device: "iPhone 8", code_coverage: true)
  
  slather(
      output_directory: "fastlane/html",
      # workspace: "Home.xcworkspace",
      html: true,
      scheme: "GithubRepoList",
      proj: "GithubRepoList.xcodeproj",
      # ignore: [ "R.generated.swift", "Pods/*"],
      verbose: true,
      show: true
  )
  end
end
